---
# tasks file for install openjdk for Solaris

- name: Solaris 11 | Install java
  block:

  - name: Solaris 11 | Install openjre
    package:
      name: "{{ openjre_package }}"
      state: present
    when: openjre_install|bool

  - name: Solaris 11 | Install openjdk
    package:
      name: "{{ openjdk_package }}"
      state: present
    when: openjdk_install|bool

  when: ansible_distribution_version|int >= 11

- name: Solaris 10 | Install java
  block:

  - name: Solaris 10 | Install openjre
    pkgutil:
      name: "{{ openjre_package }}"
      state: present
    when: openjre_install|bool

  - name: Solaris 10 | Install openjdk
    pkgutil:
      name: "{{ openjdk_package }}"
      state: present
    when: openjdk_install|bool

  - name: Solaris 10 | Add java binary to path
    file:
      src: "/opt/csw/java/jre/jre{{ java_version }}/bin/java"
      dest: "/bin/java"
      state: link

  when: ansible_distribution_version|int < 11
