- hosts: rhel7-prod
  gather_facts: true
  tasks:
  - name: importing the file contents to variable
    slurp:
      src: '/home/ansible/.ssh/id_rsa.pub'
    register: bogus_content

  - set_fact:
      pubkey: "{{ bogus_content.content | b64decode}}"

  - name: "Ansible  Print a variable if defined"
##    pubkey: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    debug:
      msg: "The 'public key to deploy' variable value is {{ pubkey }}"
    when: pubkey is defined
