- hosts: rhel7-prod
  gather_facts: true
##  vars:
##     pubkey: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
##  tasks:
##  - name: importing the file contents to variable
##    slurp:
##      src: '/home/ansible/bogus.txt'
##    register: bogus_content
##
##  - set_fact:
##      pubkey: "{{ bogus_content.content }}"
  tasks:
  - name: "Ansible  Print a variable if defined"
    pubkey: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    debug:
      msg: "The 'public key to deploy' variable value is {{ pubkey }}"
    when: pubkey is defined
