##---
- hosts: rhel7-prod
  gather_facts: no
  become: yes
  tasks:
    - name: show password
      debug:
        msg="this is the username {{uusername}} and this is the passed password before hash {{ upassword }} after hash it will become {{ upassword | password_hash('sha512') }}"

    - name: Creating user "{{ uusername }}" with admin access
      user: 
        name: "{{ uusername }}"
        password: "{{ upassword | password_hash('sha512') }}"
        groups: wheel append=yes
##  when:  assigned_role  == "yes"
##  usage: ansible-playbook create_user.yml -extra-vars="ansible_user=hhouissa uusername=ansible upassword=ansible" -ask-become-pass --ask-pass 
