
- hosts: all 
  become: yes
  vars:
    sudoers:
      - ansible
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      when:
        ansible_os_family=="RedHat"


    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
      when:
        ansible_os_family=="RedHat"


    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"
      when:
        ansible_os_family=="RedHat"


    - name: Allow sudoer user(-s) to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: 'ansible  ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
      ##with_items: "{{ sudoers }}"
      when:
        ansible_os_family=="Debian"

