---
- hosts: rhel7-prod 
  become: yes
  vars:
    sudoers:
      - ansible
  tasks:
    - name: Allow sudoer user(-s) to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: 'ansible  ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
      ##with_items: "{{ sudoers }}"
      when:
        ansible_os_family=="Debian"
