---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present
    update_cache: yes

##- name: ensure docker-py is uninstalled for pip2
##  pip:
##    name: docker-py
##    state: absent

##- name: ensure docker is uninstalled for pip3
##  pip:
##    name: docker
##    state: absent
##    executable: 3.x


- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"

