---
# we use docker as plateform
driver:
  name: vagrant

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

# Build platforms
platforms:
  # Standard Linux
  - name: centos-7
  - name: centos-6
  - name: fedora-30
  - name: fedora-29
  - name: fedora-28
  - name: fedora-27
  - name: fedora-26
  - name: ubuntu-18.04
  - name: ubuntu-17.10
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: debian-7
  - name: oraclelinux-7
    driver:
      box: bento/oracle-7
  - name: oraclelinux-6
    driver:
      box: bento/oracle-6

  # Archlinux
  - name: archlinux-rolling
    driver:
      box: archlinux/archlinux
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_archlinux_target.rb

  # Gentoo
  - name: gentoo
    driver:
      box: generic/gentoo
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_gentoo_target.rb

  # FreeBSD
  - name: freebsd-11.2
    driver:
      box: bento/freebsd-11.2
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb
  - name: freebsd-10.4
    driver:
      box: bento/freebsd-10.4
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb
  - name: freebsd-10.3
    driver:
      box: bento/freebsd-10.3
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb

  # OpenBSD
  - name: openbsd-6
    driver:
      box: generic/openbsd6
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_openbsd_target.rb

  # Mac osx
  - name: macosx-10.12
    driver:
      box: jhcook/macos-sierra
      provision: true
    provisioner:
      name: ansible_playbook
      ansible_binary_path: /usr/local/bin/
  - name: macosx-10.11
    driver:
      box: jhcook/osx-elcapitan-10.11
      provision: true
    provisioner:
      name: ansible_playbook
      ansible_binary_path: /usr/local/bin/
  - name: macosx-10.10
    driver:
      box: jhcook/osx-yosemite-10.10
      provision: true
    provisioner:
      name: ansible_playbook
      ansible_binary_path: /usr/local/bin/

suites:
  # Test openjdk-latest
  - name: openjdk-latest
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-latest.yml

  # Test openjdk-11
  - name: openjdk-11
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-11.yml
    includes:
      - oraclelinux-7
      - fedora-27
      - ubuntu-18.04
      - archlinux-rolling
      - gentoo
      - macosx-10.11
      - macosx-10.10

  # Test openjdk-10
  - name: openjdk-10
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-10.yml
    includes:
      - archlinux-rolling

  # Test openjdk-9
  - name: openjdk-9
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-9.yml
    includes:
      - fedora-27
      - fedora-26
      - ubuntu-16.04
      - gentoo
      - macosx-10.11
      - macosx-10.10

  # Test openjdk-8
  - name: openjdk-8
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-8.yml
    excludes:
      - ubuntu-14.04

  # Test openjdk-7
  - name: openjdk-7
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-7.yml
    includes:
      - oraclelinux-7
      - oraclelinux-6
      - amazonlinux-2
      - amazonlinux-1
      - debian-8
      - debian-7
      - ubuntu-14.04
      - opensuse-42.3
      - opensuse-42.2
      - opensuse-13.2
      - archlinux-rolling

  # Test openjdk-6
  - name: openjdk-6
    provisioner:
      name: ansible_playbook
      playbook: tests/playbooks/openjdk-6.yml
    includes:
      - centos-7
      - centos-6
      - oraclelinux-7
      - oraclelinux-6
      - amazonlinux-1
      - ubuntu-14.04
