---
openjre_package: '{%- if java_version == "latest" -%}
                     java-1.8.0-openjdk
                  {%- else -%}
                     java-1.{{ java_version }}.0-openjdk
                  {%- endif -%}'

openjdk_package: '{%- if java_version == "latest" -%}
                     java-1.8.0-openjdk-devel
                  {%- else -%}
                     java-1.{{ java_version }}.0-openjdk-devel
                  {%- endif -%}'
