---
# Define java version to use
openjre_package: '{%- if java_version == "latest" and ansible_distribution_major_version|int >= 30 -%}
                     java-latest-openjdk
                  {%- elif java_version == "latest" and ansible_distribution_major_version|int > 26 -%}
                     java-11-openjdk
                  {%- elif java_version == "latest" and ansible_distribution_major_version|int < 27 -%}
                     java-9-openjdk
                  {%- elif java_version == 8 -%}
                     java-1.8.0-openjdk
                  {%- else -%}
                     java-{{ java_version }}-openjdk
                  {%- endif -%}'

# Define java version to use
openjdk_package: '{%- if java_version == "latest" and ansible_distribution_major_version|int >= 30 -%}
                     java-latest-openjdk-devel
                  {%- elif java_version == "latest" and ansible_distribution_major_version|int > 26 -%}
                     java-11-openjdk-devel
                  {%- elif java_version == "latest" and ansible_distribution_major_version|int < 27 -%}
                     java-9-openjdk-devel
                  {%- elif java_version == 8 -%}
                     java-1.8.0-openjdk-devel
                  {%- else -%}
                     java-{{ java_version }}-openjdk-devel
                  {%- endif -%}'
